### ISSUE TITLE
11 Test Failures in lib-blockchain After Compilation Fixes

### ISSUE THREAD

**Issue by umwelt** [SOVEREIGN-NET/The-Sovereign-Network#125]
# Test Failures in lib-blockchain After Compilation Fixes

## Summary
After fixing all compilation errors in PR #120 (Issue #111), the test suite now runs successfully but reveals 11 pre-existing test failures in lib-blockchain. These tests were never running before due to compilation errors.

## Impact
- **Build**: ✅ Passes (0 errors)
- **Test Compilation**: ✅ Passes (0 errors)  
- **Test Execution**: ❌ 11 failures out of 191 tests (94% pass rate)

### Web4 Contract Tests (2 failures)
1. **`contracts::web4::core::tests::test_add_remove_route`**
   - Location: `lib-blockchain/src/contracts/web4/core.rs:961`
   - Error: `assertion failed: add_result.is_ok()`
   - Description: Route addition fails when it should succeed

2. **`contracts::web4::core::tests::test_domain_validation`**
   - Location: `lib-blockchain/src/contracts/web4/core.rs:904`
   - Error: `assertion failed: !Web4Contract::is_valid_domain("invalid-.zhtp")`
   - Description: Domain validation incorrectly accepts invalid domain names

### Edge Node State Tests (3 failures)
3. **`edge_node_state::tests::test_header_rolling_window`**
   - Location: `lib-blockchain/src/edge_node_state.rs:595`
   - Error: `assertion failed: edge_node.get_latest_header().is_some()`
   - Description: Latest header is None when it should be Some

4. **`edge_node_state::tests::test_needs_bootstrap_proof`**
   - Location: `lib-blockchain/src/edge_node_state.rs:609`
   - Error: `assertion failed: !edge_node.needs_bootstrap_proof(500)`
   - Description: Bootstrap proof requirement logic incorrect

5. **`edge_node_state::tests::test_sync_strategy_close_to_tip`**
   - Location: `lib-blockchain/src/edge_node_state.rs:652`
   - Error: `Expected HeadersOnly when close to tip`
   - Description: Sync strategy selection incorrect for nodes close to chain tip

### Economic Integration Tests (3 failures)
6. **`integration::economic_integration::tests::test_fee_calculation`**
   - Location: `lib-blockchain/src/integration/economic_integration.rs:762`
   - Error: `assertion left == right failed: left: 250, right: 0`
   - Description: Fee calculation returns 0 instead of expected 250

7. **`integration::economic_integration::tests::test_payment_transaction_creation`**
   - Error: `Insufficient balance: need 1270 ZHTP, have 0 ZHTP`
   - Description: Test identity has no balance for payment transaction

8. **`integration::economic_integration::tests::test_ubi_distribution_creation`**
   - Location: `lib-blockchain/src/integration/economic_integration.rs:717`
   - Error: `assertion failed: tx.memo.starts_with(b"Economic TX: UBI Distribution")`
   - Description: UBI transaction memo has wrong format

### Storage Integration Tests (2 failures)
9. **`integration::storage_integration::tests::test_block_storage_and_retrieval`**
   - Error: `Content decryption failed: aead::Error`
   - Description: Block storage/retrieval fails on decryption

10. **`integration::storage_integration::tests::test_blockchain_state_storage_and_retrieval`**
    - Error: `Content decryption failed: aead::Error`
    - Description: Blockchain state storage/retrieval fails on decryption

### Network Integration Test (1 failure)
11. **`integration::network_integration::tests::test_network_node`**
    - Location: `lib-blockchain/src/integration/network_integration.rs:259`
    - Error: `assertion failed: node.last_seen > old_last_seen`
    - Description: Network node last_seen timestamp not updating

### Decryption Errors
Tests 9-10 fail due to encryption key mismatches or uninitialized encryption in test setup.

### Balance/Economic Issues  
Tests 6-8 fail because test identities are created without initial balances or proper economic setup.

### Edge Node Logic
Tests 3-5 fail due to incorrect assumptions about edge node state management and header tracking.

### Web4 Validation
Tests 1-2 fail due to bugs in domain validation logic and route management.

### Network Timing
Test 11 fails due to timing/race condition where last_seen doesn't update in test timeframe.

## Priority
**P1 - High**: These failures block the test suite from being a reliable CI check. While the code compiles and builds successfully, we cannot trust the test suite until these are fixed.

## Related Issues
- #111 - Test compilation errors (FIXED in PR #120)
- PR #120 - Fix compilation errors and test warnings

## Next Steps
1. Fix decryption errors in storage integration tests (likely missing test setup)
2. Fix economic integration tests by adding initial balances to test identities
3. Fix edge node state logic bugs
4. Fix Web4 domain validation regex/logic
5. Fix network timing test (add explicit timestamp update or use mock time)

## Test Output
Full test run shows:
```
test result: FAILED. 177 passed; 14 failed; 0 ignored; 0 measured; 0 filtered out
```

Note: 3 failures were already fixed in commit 464fdad, reducing from 14 to 11 remaining failures.
